#!/bin/bash
# install
# 
# Quick Description:
# Part of the CQUATS - C QA ToolSet - project
# 
# CQuATS Configuration Menu System.
# Menu is based on the opensource Kbuild system;
# initial template sourced from here:
#  https://github.com/masahir0y/kbuild_skeleton
# All credit to the original devs.
#
# Last Updated : 13Nov2017
# Created      : 20Sep2017
# License: GPLv2
name=$(basename $0)
INSTDIR=/usr/share/cquats
INST_DIRS=(kbuild tools)
INST_FILES=(color.sh cquats_common.sh menuconfig README.md common.sh \
err_common.sh LICENSE README_dev run_cquats)


[ $(id -u) -ne 0 ] && {
  echo "${name}: need root access to install CQuATS."
  exit 1
}

[ -d ${INSTDIR} ] && {
  echo "${name}: the CQuATS system seems to already be installed.
  [FYI, here: ${INSTDIR} :
  $(ls -al ${INSTDIR})
  ]
  Aborting install..."
#  exit 1
}

echo "CQuATS installation proceeding ..."
mkdir -p ${INSTDIR}

# Copy files across
for afile in "${INST_FILES[@]}"
do
  printf "%20s --> %s\n" ${afile} ${INSTDIR}
  cp -u ${afile} ${INSTDIR} || {
    echo "${name}: cp failed [status=$?], aborting..." ; exit 1
  }
done

# Copy folders across
for afolder in "${INST_DIRS[@]}"
do
  printf "%20s/ --> %s\n" ${afolder} ${INSTDIR}
  cp -au ${afolder} ${INSTDIR}/ || {
    echo "${name}: cp failed [status=$?], aborting..." ; exit 1
  }
done
chown -R root:root ${INSTDIR}

#echo "${name}: install dir: ${INSTDIR}"
#ls -l ${INSTDIR}

echo "${name}: installation successful."
exit 0





######### first time
[ -f .first ] && {
  cd kbuild || exit 1
  # mconf is the binary executable used for the 'menuconfig' target
  make distclean   #mrproper
  rm -f scripts/kconfig/mconf ../.first
} |tee -a ${LOGFILE_COMMON}
#########

{
check_deps "gcc make"  #perf spatch xterm"

# Running the 'make menuconfig' in a subshell seems to help
(cd ${MENUDIR} ; \
echo "${gPRJ}:${name}: menu system loading, pl wait ..." ; make menuconfig )
} #|tee -a ${LOGFILE_COMMON}

exit 0
