#!/bin/bash
# cr8_cquats_tarxz.sh
# 
# Last Updated :
# Created      :
# 
# Author:
# Kaiwan N Billimoria
# kaiwan -at- kaiwantech -dot- com
# kaiwanTECH
# 
# GPLv2.
# 
name=$(basename $0)
CQUATS_SRC=/home/kai/cquats/src

tarit()
{
echo "[+] tar-ring now ..."
tar cJf $1 --directory=${CQUATS_SRC}/ . || {
  echo "Oops!" ; exit 1
}
ls -lh $1
  # (c)reate (J)xz-compression (f)iles-follow
}


##### 'main' : execution starts here #####

[ $# -ne 1 ] && {
  echo "Usage: ${name} create-pathname-cquats.tar.xz"
  exit 1
}
cd ${CQUATS_SRC}/kbuild
# mconf is the binary executable used for the 'menuconfig' target
rm -f .config*

make distclean
rm -f scripts/kconfig/mconf

# Use env vars to figure out:
# a) CQ_INST=1 => install_prep; has the make skip running 'mconf Kconfig'
#    (we want it like this; the menu shouldn't come up during installation.
#    conversely, when the user runs CQuATS menuconfig after install, CQ_INST
#    isn't defined and the menu shows up!
#     Makefile where we query CQ_INST: kbuild/scripts/kconfig/Makefile
# b) UCONFDIR : set to the location where it can find the .config file
#     Makefile loc: kbuild/Makefile
echo "[+] Build kconfig :: CQ_INST=1 UCONFDIR=. make V=1"
CQ_INST=1 UCONFDIR=. make V=1 menuconfig

cd - >/dev/null

tarit $1

exit 0
