#!/bin/bash
# install_system
# 
# Quick Description:
# Part of the CQUATS - C QA ToolSet - project
# The stand-alone System Install script;
# installs CQuATS into /usr/share/cquats ..
#
# Last Updated : 14Nov2017
# Created      : 20Sep2017
# License: GPLv2
name=$(basename $0)
INSTDIR=/usr/share/cquats
INST_DIRS=(kbuild tools)
INST_FILES=(color.sh cquats_common.sh menuconfig README.md common.sh \
err_common.sh LICENSE README_dev run_cquats)
LOCAL_FILES_DELETE=(menuconfig run_cquats color.sh common.sh err_common.sh)

[ $(id -u) -ne 0 ] && {
  echo "${name}: need root access to install CQuATS."
  exit 1
}

[ -d ${INSTDIR} ] && {
  echo "${name}: the CQuATS system seems to ALREADY be installed.

  [FYI, over here: ${INSTDIR} ]
  Aborting install...
  
  Try running the install_local program to install CQuATS for you locally,\
 as a regular user, not root."
  exit 1
}

echo "CQuATS Installation Part 1 - System Install - proceeding ..."
mkdir -p ${INSTDIR}

# Copy files across
for afile in "install_system install_local ${INST_FILES[@]}"
do
  printf "%20s --> %s\n" ${afile} ${INSTDIR}
  cp -u ${afile} ${INSTDIR} || {
    echo "${name}: cp failed [status=$?], aborting..." ; exit 1
  }
done

# Copy folders across
for afolder in "${INST_DIRS[@]}"
do
  printf "%20s/ --> %s\n" ${afolder} ${INSTDIR}
  cp -au ${afolder} ${INSTDIR}/ || {
    echo "${name}: cp failed [status=$?], aborting..." ; exit 1
  }
done
chown -R root:root ${INSTDIR}

# Now delete the src files from here, the 'local' folder..
for afile in "${LOCAL_FILES_DELETE[@]}"
do
  rm -f ${afile}
done
for afolder in "${INST_DIRS[@]}"
do
  rm -rf ${afolder}
done

#echo "logname=${LOGNAME} user=${USER}"
#echo "${name}: install dir: ${INSTDIR}"
#ls -l ${INSTDIR}

echo "${name}: CQuATS System Installation Part 1 successful.

Now pl run the install_local program, as a regular user (not root), \
to install CQuATS locally for you."
exit 0
