#!/bin/bash
# install2
# 
# Quick Description:
# Part 2 of the CQuATS framework install.
# Must be invoked by the first part, i.e., install_cquats .
#
# Part of the CQUATS - C QA ToolSet - project
# installs CQuATS into /usr/share/cquats ..
#
# Last Updated : 16Nov2017
# Created      : 20Sep2017
# License: GPLv2
name=$(basename $0)
INSTDIR=/usr/share/cquats

runMsg="Run CQuATS (as a regular user, not root) ::
 ${INSTDIR}/menuconfig
 ${INSTDIR}/run_cquats"

[ $(id -u) -ne 0 ] && {
  echo "${name}: need root access to install CQuATS."
  exit 1
}

[ -d ${INSTDIR} ] && {
  echo "${name}: the CQuATS system seems to ALREADY be installed.

  [FYI, over here: ${INSTDIR} ]
  Aborting install...
  
${runMsg}"
  exit 1
}

[ $# -ne 1 ] && {
  echo "Usage: ${name} pathname-to-cquats-tarball"
  exit 1
}
[ ! -f $1 ] && {
  echo "${name}: pathname-to-cquats-tarball \"$1\" invalid."
  exit 1
}

echo "CQuATS System Installation proceeding ..."
mkdir -p ${INSTDIR} || exit 1

echo " [+] eXtracting tarball \"$1\" into \"${INSTDIR}\" now ..."
tar xf ${1} -C ${INSTDIR}/ || {
  echo "Oops! extraction failed" ; exit 1
}
chown -R root:root ${INSTDIR}/

echo " and done.
${name}: CQuATS System Installation successful.

${runMsg}"

exit 0
