#!/bin/bash
# install_local
# 
# Quick Description:
# Part of the CQUATS - C QA ToolSet - project
#  The 'local' installer script.
#
# Last Updated : 14Nov2017
# Created      : 20Sep2017
# License: GPLv2
name=$(basename $0)
PFX=$(dirname $(which $0))
source ${PFX}/cquats_common.sh || {
 echo "${name}: fatal: could not source ${PFX}/cquats_common.sh , aborting..."
 exit 1
} |tee -a ${LOGFILE_COMMON}

RUN_MSG_HOWTO="
CQuATS is locally installed here:
${LOCAL_INSTDIR}

To run CQuATS, from a terminal window or shell, do:
   cd ${LOCAL_INSTDIR}/
   ./menuconfig
   ./run_cquats
"

[ $(id -u) -eq 0 ] && {
  echo "CQuATS :: Local Install should Not be done as root user, aborting..."
  exit 1
}
[ ! -d ${INSTDIR} ] && {
  echo "CQuATS :: System Install does not seem to be done.
First proceed with the CQuATS system installation by running the \
install_system script."
  exit 1
}
[ -d ${LOCAL_INSTDIR} ] && {
  echo "CQuATS :: Local Install (for user \"${LOGNAME}\") is already done ...
${RUN_MSG_HOWTO}"
  exit 1
}

{
  mkdir -p ${LOCAL_INSTDIR}
  cd ${LOCAL_INSTDIR} || exit 1
  echo "[+] CQuATS :: First run detected, setting up Local Install for user \"${LOGNAME}\" now ..."
  mkdir -p ${gCQUATS_SCRATCH_FOLDER} 2>/dev/null
  cp -a ${INSTDIR}/* .
  touch .first
  rm -f ${MENUDIR}/.config*

  echo "Done.
${RUN_MSG_HOWTO}"
  exit 0
} |tee -a ${LOGFILE_COMMON}
exit 0
