#!/bin/bash
# install_cquats
# 
# The CQuATS framework 'distro' installer script.
# Currently tested on Fedora 26 only.
#
# Last Updated : 16Nov2017
# Created      :
# 
# Author:
# Kaiwan N Billimoria
# kaiwan -at- kaiwantech -dot- com
# kaiwanTECH
# 
# GPLv2.
# 
name=$(basename $0)
CQUATS_TAR=cquats.tar.xz
INSTDIR=/usr/share/cquats

tarit()
{
echo "[+] tar-ring now ..."
tar cJf $1 --directory=${CQUATS_SRC}/ . || {
  # (c)reate (J)xz-compression (f)iles-follow
  echo "Oops! tar cJf failed" ; exit 1
}
ls -lh $1
}


##### 'main' : execution starts here #####

INSTDIR=/usr/share/cquats

runMsg="Run CQuATS (as a regular user, not root) ::
 ${INSTDIR}/menuconfig
 ${INSTDIR}/run_cquats"

[ $(id -u) -ne 0 ] && {
  echo "${name}: need root to install CQuATS."
  exit 1
}
[ $# -ne 1 ] && {
  echo "Usage: ${name} cquats-source-folder"
  exit 1
}
[ ! -d $1 ] && {
  echo "${name}: cquats-source-folder \"$1\" invalid."
  exit 1
}
CQUATS_SRC=$1

[ -d ${INSTDIR} ] && {
  echo "${name}: the CQuATS system seems to ALREADY be installed.

  [FYI, over here: ${INSTDIR} ]
  Aborting install...

${runMsg}"
  exit 1
}

## Build deps: <- Check
#   gcc, ncurses-devel
which gcc >/dev/null || {
  echo "${name}: 'gcc' package required, pl install and retry..."
  exit 1
}
rpm -qa|grep ncurses-devel >/dev/null || {
  echo "${name}: 'ncurses-devel' package required, pl install and retry..."
  exit 1
}

cd ${CQUATS_SRC}/kbuild

# mconf is the binary executable used for the 'menuconfig' target
rm -f .config*
make distclean
rm -f scripts/kconfig/mconf

# Use env vars to figure out:
# a) CQ_INST=1 => install_prep; has the make skip running 'mconf Kconfig'
#    (we want it like this; the menu shouldn't come up during installation.
#    conversely, when the user runs CQuATS menuconfig after install, CQ_INST
#    isn't defined and the menu shows up!
#     Makefile where we query CQ_INST: kbuild/scripts/kconfig/Makefile
# b) UCONFDIR : set to the location where it can find the .config file
#     Makefile loc: kbuild/Makefile
echo "[+] Build kconfig :: CQ_INST=1 UCONFDIR=. make V=1"
CQ_INST=1 UCONFDIR=. make menuconfig

cd - >/dev/null

tarit ${CQUATS_TAR}

# Now for the 2nd part of the Install...
echo "[+] CQuATS System Installation proceeding ..."
mkdir -p ${INSTDIR} || exit 1

echo " [+] eXtracting tarball \"${CQUATS_TAR}\" into \"${INSTDIR}\" now ..."
tar xf ${CQUATS_TAR} -C ${INSTDIR}/ || {
  echo "Oops! extraction failed" ; exit 1
}
chown -R root:root ${INSTDIR}/

echo " and done.
${name}: CQuATS System Installation successful.

${runMsg}"
exit 0
