#!/bin/bash
# configure
# 
# Quick Description:
# Part of the CQUATS - C QA ToolSet - project
# 
# CQuATS Configuration Menu System.
# Menu is based on the opensource Kbuild system;
# initial template sourced from here:
#  https://github.com/masahir0y/kbuild_skeleton
# All credit to the original devs.
#
# Last Updated :
# Created      : 20Sep2017
# License: GPLv2
name=$(basename $0)
PFX=$(dirname `which $0`)
source ${PFX}/common.sh || {
 echo "${name}: fatal: could not source ${PFX}/common.sh , aborting..."
 [ "${parent}" = "bash" ] && exit 1 || return 1
}
source ${PFX}/cquats_common.sh || {
 echo "${name}: fatal: could not source ${PFX}/cquats_common.sh , aborting..."
 [ "${parent}" = "bash" ] && exit 1 || return 1
} |tee -a ${LOGFILE_COMMON}

######### first time
[ -f .first ] && {
  cd kbuild || exit 1
  # mconf is the binary executable used for the 'menuconfig' target
  make distclean   #mrproper
  rm -f scripts/kconfig/mconf ../.first
} |tee -a ${LOGFILE_COMMON}
#########

{
check_deps "gcc make"  #perf spatch xterm"

# Running the 'make menuconfig' in a subshell seems to help
(cd ${MENUDIR} ; \
echo "${gPRJ}:${name}: menu system loading, pl wait ..." ; make menuconfig )
} #|tee -a ${LOGFILE_COMMON}

exit 0
